language: node_js
node_js:
  - "0.10"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
notifications:
  email:
    - carhoden@gmail.com
script:
  - "npm test"
  - "node ./node_modules/.bin/istanbul check-coverage --statements 90 --branches 75 --lines 90 --functions 90"

